export const environment = {
  production: true,
  apiUrl: 'https://api.yahallo.com',
  mangaApi: 'https://api.yahallo.com/manga',
  chapterApi: 'https://api.yahallo.com/chapter',
  commentApi: 'https://api.yahallo.com/comment',
  userApi: 'https://api.yahallo.com/user',
  tagApi: 'https://api.yahallo.com/tag',
  artistApi: 'https://api.yahallo.com/artist',
  authorApi: 'https://api.yahallo.com/author',
  followMangaApi: 'https://api.yahallo.com/follow-manga',
  mangaTagApi: 'https://api.yahallo.com/manga-tag',
  roleApi: 'https://api.yahallo.com/role',
  userRoleApi: 'https://api.yahallo.com/user-role',
  serviceApi: 'https://api.yahallo.com/services',
  readingProgressApi: 'https://api.yahallo.com/reading-progress',
  notificationApi: 'https://api.yahallo.com/notification',
  subscriptionApi: 'https://api.yahallo.com/subscription',
  securityApi: 'https://api.yahallo.com/security',
  hubUrl: 'https://api.yahallo.com/hubs/notification',
};
