export const environment = {
  production: true,
  apiUrl: 'https://api.yahallo.online',
  ratingApi: 'https://api.yahallo.online/rating',
  mangaApi: 'https://api.yahallo.online/manga',
  chapterApi: 'https://api.yahallo.online/chapter',
  chapterImageApi: 'https://api.yahallo.online/chapter-image',
  commentApi: 'https://api.yahallo.online/comment',
  userApi: 'https://api.yahallo.online/user',
  tagApi: 'https://api.yahallo.online/tag',
  artistApi: 'https://api.yahallo.online/artist',
  authorApi: 'https://api.yahallo.online/author',
  followMangaApi: 'https://api.yahallo.online/follow-manga',
  mangaTagApi: 'https://api.yahallo.online/manga-tag',
  roleApi: 'https://api.yahallo.online/role',
  userRoleApi: 'https://api.yahallo.online/user-role',
  serviceApi: 'https://api.yahallo.online/services',
  readingProgressApi: 'https://api.yahallo.online/reading-progress',
  userSettingsApi: 'https://api.yahallo.online',
  notificationApi: 'https://api.yahallo.online/notification',
  subscriptionApi: 'https://api.yahallo.online/subscription',
  securityApi: 'https://api.yahallo.online/security',
  countryApi: 'https://api.yahallo.online/country',
  hubUrl: 'https://api.yahallo.online/hubs/notification',
};
