export const environment = {
  production: false,
  apiUrl: 'https://localhost:7181',
  mangaApi: 'https://localhost:7181/manga',
  userApi: 'https://localhost:7181/user',
  serviceApi: 'https://localhost:7181/services',
  tagApi: 'https://localhost:7181/tag',
  readingProgressApi: 'https://localhost:7181/reading-progress',
  notificationApi: 'https://localhost:7181/notification',
  subscriptionApi: 'https://localhost:7181/subscription',
  hubUrl: 'https://localhost:7181/hubs/notification',
  artistApi: 'https://localhost:7181/artist',
  authorApi: 'https://localhost:7181/author',
  chapterApi: 'https://localhost:7181/chapter',
  commentApi: 'https://localhost:7181/comment',
  followApi: 'https://localhost:7181/follow-manga',
  mangaTagApi: 'https://localhost:7181/manga-tag',
  roleApi: 'https://localhost:7181/role',
  securityApi: 'https://localhost:7181/security',
};
